<?php

include_once('panopoly_pages.features.inc');

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function panopoly_pages_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_panelizer_default_types_alter()
 */
function panopoly_pages_panelizer_defaults_alter(&$defaults) {
  // Require the panels panelizer include from features since 
  // features doesn't support hook_panelizer_defaults() correctly.
  // See https://drupal.org/node/1427150 for more on that.
  require_once('panopoly_pages.panelizer.inc');
  foreach(panopoly_pages_panelizer_defaults() as $name => $default) {
    $defaults[$name] = $default;
  }
}
